plugins { id 'com.android.application' }

android {
    namespace 'com.superme.telegram07'
    compileSdk 35

    defaultConfig {
        applicationId 'com.superme.telegram07'
        minSdk 23
        targetSdk 35
        versionCode 3
        versionName '1.2'
        buildConfigField 'String', 'SERVICES_BASE_URL', '"https://messenger-clone-zbef.onrender.com/"'
    }
}
